global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'phoenix_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:9568']
        labels:
          app: 'whoknows_elixir_monolith'
